### ISSUE TITLE
What to learn from Tokeet and Smartbnb

### ISSUE THREAD

**Issue by davidboom95** [zxol/airbnbapi#11]
Hi, 
Im using Smartbnb and Tokeet for two months now. I've seen some common characteristics on them, I think they have no real API integration. Maybe we could learn something about Airbnb API from their login process.

**When you register your Airbnb account. You should go to an Airbnb page and make a Captcha verification.**
- Where does this link comes from? What data is passed in the URL?
- It is mandatory to make a Captcha to validate phone, mail verification code? As we saw on [AirbnbApi Verification EndPoints](http://apidirectory.org/airbnbapi/index.php?title=Verification_Endpoints) We can make a request to an URL
- We have to Captcha, it means Airbnb identifies the petition as a Robot, So... They use Proxy or not?

**Smartbnb makes updates every 30 seconds.**
- Why? What is the petition limit per second/minutes?

**Comment by zxol** [comment]
Hey David, thanks for the message!  Looks like we already have an issue #3 open for the airlock/security issue.  

I can't comment on smartbnb and tokeet as I haven't used them.

There is definitely a rate limit on the mobile API.   I haven't run any tests but I found setting the polling rate to below 40 seconds would sometimes receive a temporary block to the service for an hour or two.  The algorithm seems to be some kind of rolling count that blocks you if your average request speed is too high.  Either that, or they give each 'user' a hard allowance per hour.  

If you're curious, why not do some testing yourself?

**Comment by davidboom95** [comment]
Thank you for your answer, 
So, I can get the auth token once in a while.
But if I want to make frequent requests with this API to ~60 accounts.
I should limit to a request per minute, Maybe there is something more to do?
