### ISSUE TITLE
_format=for_mobile_host

### ISSUE THREAD

**Issue by petrce** [zxol/airbnbapi#14]
Hi,
with get all reservations, I am getting 403 forbidden for _format=for_mobile_host
_format=for_mobile_guest is working well.
Did Airbnb change the API?
Thanks
Petr

**Comment by zxol** [comment]
I will test this today.

**Comment by zxol** [comment]
getReservations is working fine for me with the _format=for_mobile_host. 

Perhaps I need to write some functions for the guest side of things.
