### ISSUE TITLE
all listingSearch for country?

### ISSUE THREAD

**Issue by intergleam** [zxol/airbnbapi#15]
I am trying to download all listings for Georgia, if i set `location: 'Georgia, GE',` which seems to work, the  `offset: 500`, brings an empty list already. Any idea how to get all listings without looping through towns? 

Thanks for awesome project!!

**Comment by zxol** [comment]
I'm sorry, I don't know if that's possible.  When I was making a list of all listings in Tokyo, I had to search by prefecture, covering as much area as possible, and then deleting the overlapping listings.  It's a pain.  

I guess they limit it server side for performance reasons.
