### ISSUE TITLE
no ability to set start/end date for listingSearch ? or rental type?

### ISSUE THREAD

**Issue by vesper8** [zxol/airbnbapi#18]
am I missing something? this seems like one of the most important filters when searching for listings.. nearly all filters are available but I can't find how to set the date range.. I mean.. if I want to see listings available between June 1st and June 30th for example.

Also would be lovely to add the "rental type" filter.. eg 'shared room', 'full apartment', etc

Thanks a lot for your contribution! Looking forward to future updates

**Comment by zxol** [comment]
Thanks for letting me know! I've just published a new version with date ranges on the searchlistings.

the new properties are called `checkin` and `checkout` and they accept ISO like dates, i.e. `"2020-01-21"`

I'll have a look at the rental type now.

**Comment by zxol** [comment]
I've just added more properties including the rental type.  I'll close this issue now.

**Comment by vesper8** [comment]
awesome!! thank you!
