### ISSUE TITLE
Specialist is required

### ISSUE THREAD

**Issue by jjnini** [zxol/airbnbapi#20]
As I need a specialist for AirBnB API integration with our current system I would like to know if an expert can help to finalize our project
Thanks

**Comment by zxol** [comment]
How do I get in touch with you?

**Comment by jjnini** [comment]
hi
how can we ?
I have email, phone, Skype ..
I'll be more then interested discussing with you

Regards

**Comment by jjnini** [comment]
Hi

Can you contact me using email?

 

Cordialement, 

 

JJ NINI

 

JKC Finance

0183835083

 

De : Andy Mac <notifications@github.com> 
Envoyé : samedi 11 mai 2019 10:48
À : zxol/airbnbapi <airbnbapi@noreply.github.com>
Cc : jjnini <jj.nini@jkc-finance.com>; Author <author@noreply.github.com>
Objet : Re: [zxol/airbnbapi] Specialist is required (#20)

 

How do I get in touch with you?

**Comment by jjnini** [comment]
Hi
I need a contact in emergency
Please tell me how to proceed
Regards

**Comment by zxol** [comment]
I've contacted you via email.

**Comment by jjnini** [comment]
Hello

I need to have an expert to quote my project

Can we have a discussion over phone or Skype?

 

Cordialement, 

 

JJ NINI

 

JKC Finance

0183835083

 

De : Andy Mac <notifications@github.com> 
Envoyé : mardi 14 mai 2019 05:27
À : zxol/airbnbapi <airbnbapi@noreply.github.com>
Cc : jjnini <jj.nini@jkc-finance.com>; Comment <comment@noreply.github.com>
Objet : Re: [zxol/airbnbapi] Specialist is required (#20)

 

I've contacted you via email.
