### ISSUE TITLE
Currency setting is not used for all requests

### ISSUE THREAD

**Issue by mastef** [zxol/airbnbapi#23]
buildOptions defaults currency to `JPY`:
```
    buildOptions({
        token,
        method = 'GET',
        route = '/v2/batch',
        uri,
        json = true,
        headers,
        currency = 'JPY',
        format,
        qs,
        body,
        timeout,
        proxy
    })
```

Even if you use `airbnb.setCurrency('USD');` or ```
airbnb.setConfig({
    currency: 'USD'
});
``` the requests are being sent with `qs.currency: 'JPY'` unless specifically set in the method. So e.g. if you ping `getOwnListings`, you'll get all prices in `JPY` currency.

Maybe add something in `buildOptions` to respect the config, instead of the default values there.

**Comment by zxol** [comment]
Thank you for tracking down this bug!  I'll update the package today with
`currency = this.config.currency,`

**Comment by zxol** [comment]
I've updated the package with the fix and published it.
